/** All UI copy, Bengali + English. Keep keys grouped by page/feature. */
type Entry = { bn: string; en: string };
export const dict: Record<string, Entry> = {
  // ── Common chrome ──
  'nav.home': { bn: 'হোম', en: 'Home' },
  'nav.map': { bn: 'প্যান্ডেল ম্যাপ', en: 'Pandal map' },
  'nav.advertise': { bn: 'বিজ্ঞাপন দিন', en: 'Advertise' },
  'nav.policies': { bn: 'যোগাযোগ ও নীতি', en: 'Contact & policies' },
  'skip': { bn: 'মূল অংশে যান', en: 'Skip to content' },
  'sponsored': { bn: 'স্পনসর', en: 'Sponsored' },
  'adhere.cta': { bn: 'এখানে আপনার বিজ্ঞাপন — {price} থেকে · বুক করুন', en: 'Your brand here — from {price} · Book now' },

  // ── Hero / countdown ──
  'hero.kicker': { bn: 'শনিবার, ১০ অক্টোবর ২০২৬ · ভোর', en: 'Saturday, 10 October 2026 · before dawn' },
  'hero.title': { bn: 'শুভ মহালয়া', en: 'Shubho Mahalaya' },
  'hero.sub': {
    bn: 'ভোরের আঁধারে মহিষাসুরমর্দিনী — আকাশবাণীর সরকারি লাইভ স্ট্রিমে, এই পাতা থেকেই।',
    en: 'Mahishasuramardini in the pre-dawn dark — on Akashvani’s official live stream, right from this page.',
  },
  'hero.kicker.puja': { bn: 'দুর্গাপুজো ২০২৬ · ১৬–২১ অক্টোবর', en: 'Durga Puja 2026 · 16–21 October' },
  'hero.title.puja': { bn: 'শুভ শারদীয়া', en: 'Shubho Sharodiya' },
  'hero.sub.puja': {
    bn: 'পুজোর গান শুনুন, ঢাক বাজান, আর প্যান্ডেল ম্যাপ দেখে ঠাকুর দেখতে বেরিয়ে পড়ুন।',
    en: 'Play Puja songs, tap the dhak, and head out pandal-hopping with the map.',
  },
  'hero.kicker.bijoya': { bn: 'বিজয়া দশমী ২০২৬', en: 'Bijoya Dashami 2026' },
  'hero.title.bijoya': { bn: 'শুভ বিজয়া', en: 'Shubho Bijoya' },
  'hero.sub.bijoya': { bn: 'আসছে বছর আবার হবে। মহালয়ার রেকর্ডিং আর পুজোর গান নিচে রইল।', en: 'Until next year. Mahalaya recordings and Puja songs are below.' },
  'cd.toMahalaya': { bn: 'মহিষাসুরমর্দিনী শুরু হতে বাকি', en: 'Mahishasuramardini begins in' },
  'cd.live': { bn: 'এখন সম্প্রচার চলছে — নিচে প্লে করুন', en: 'On air now — press play below' },
  'cd.toShashthi': { bn: 'মহাষষ্ঠী আসতে বাকি', en: 'Maha Shashthi arrives in' },
  'cd.pujo': { bn: 'পুজো এসে গেছে! আজ {day}', en: 'Pujo is here! Today is {day}' },
  'cd.over': { bn: 'শুভ বিজয়া! আসছে বছর আবার হবে।', en: 'Shubho Bijoya! See you again next year.' },
  'cd.days': { bn: 'দিন', en: 'days' },
  'cd.hours': { bn: 'ঘণ্টা', en: 'hours' },
  'cd.minutes': { bn: 'মিনিট', en: 'min' },
  'cd.seconds': { bn: 'সেকেন্ড', en: 'sec' },
  'cd.ist': { bn: 'ভারতীয় সময়', en: 'India time (IST)' },
  'cd.local': { bn: 'আপনার সময়', en: 'Your time' },
  'cd.by': { bn: 'কাউন্টডাউন সৌজন্যে', en: 'Countdown by' },

  'ui.close': { bn: 'বন্ধ করুন', en: 'Close' },
  'dock.label': { bn: 'আরও', en: 'More' },
  'dock.schedule': { bn: 'নির্ঘণ্ট', en: 'Schedule' },
  'dock.songs': { bn: 'গান', en: 'Songs' },
  'dock.dhak': { bn: 'ঢাক', en: 'Dhak' },
  'dock.faq': { bn: 'প্রশ্নোত্তর', en: 'FAQ' },
  'mc.badge': { bn: 'উত্তর · দক্ষিণ কলকাতা', en: 'North · South Kolkata' },
  'mc.title': { bn: 'প্যান্ডেল ম্যাপ ২০২৬', en: 'Pandal map 2026' },
  'mc.sub': { bn: '৫০টিরও বেশি প্যান্ডেল — আপনার কাছের পুজো খুঁজুন, এক চাপে রাস্তা পান।', en: '50+ pandals — find the pujas near you and get directions in one tap.' },
  'mc.f1': { bn: '📍 আমার কাছে', en: '📍 Near me' },
  'mc.f2': { bn: '🚇 কাছের মেট্রো', en: '🚇 Nearest metro' },
  'mc.f3': { bn: '🧭 গুগল ম্যাপস ডিরেকশন', en: '🧭 Google Maps directions' },
  'mc.cta': { bn: 'ম্যাপ খুলুন', en: 'Open the map' },
  'welcome.mute': { bn: 'ঢাক বন্ধ করুন', en: 'Turn off dhak' },
  'dock.map': { bn: 'প্যান্ডেল ম্যাপ', en: 'Pandal map' },
  'rem.gcalShort': { bn: 'গুগল ক্যালেন্ডার', en: 'Google Calendar' },
  'rem.icsShort': { bn: '.ics রিমাইন্ডার', en: '.ics reminder' },
  'rem.waShort': { bn: 'শেয়ার', en: 'Share' },
  'radio.noteShort': {
    bn: '১০ অক্টোবর ভোর ৩:৫০–৫:৪৫ (ভারতীয় সময়) · সম্প্রচার ও স্বত্ব: প্রসার ভারতী / আকাশবাণী',
    en: '10 Oct, 3:50–5:45 AM IST · Broadcast © Prasar Bharati / Akashvani',
  },
  'radio.fallbackMw': { bn: 'MW ৬৫৭ kHz', en: 'MW 657 kHz' },
  'wake.how': { bn: 'কীভাবে কাজ করে', en: 'How it works' },
  'slot.spotlight': { bn: 'স্পটলাইট কার্ড', en: 'Spotlight card' },
  'slot.spotlight.where': { bn: 'হোম পেজের ছবির উপর, ডান দিকে (রেডিও প্লেয়ার থেকে দূরে)', en: 'On the home hero image, right side (away from the radio player)' },
  // ── Radio ──
  'radio.title': { bn: 'লাইভ রেডিও', en: 'Live radio' },
  'radio.note': {
    bn: 'সরকারি তালিকা অনুযায়ী ১০ অক্টোবর ভোর ৩:৫০ থেকে ৫:৪৫ (ভারতীয় সময়) কলকাতা কেন্দ্র থেকে মহালয়ার বিশেষ অনুষ্ঠান। অন্য সময়ে চ্যানেলের নিয়মিত অনুষ্ঠান শোনা যাবে।',
    en: 'Per the official schedule, Kolkata’s special Mahalaya transmission runs 3:50–5:45 AM IST on 10 Oct. At other times you’ll hear the channel’s regular programmes.',
  },
  'radio.channel': { bn: 'চ্যানেল', en: 'Channel' },
  'radio.play': { bn: 'শুনুন', en: 'Play' },
  'radio.pause': { bn: 'থামান', en: 'Pause' },
  'radio.live': { bn: 'লাইভ', en: 'LIVE' },
  'radio.idle': { bn: 'প্লে চাপলে আকাশবাণীর লাইভ স্ট্রিম চালু হবে', en: 'Press play to start Akashvani’s live stream' },
  'radio.loading': { bn: 'সংযোগ হচ্ছে…', en: 'Connecting…' },
  'radio.buffering': { bn: 'বাফারিং…', en: 'Buffering…' },
  'radio.playing': { bn: 'সরাসরি শুনছেন: {ch}', en: 'Listening live: {ch}' },
  'radio.paused': { bn: 'থামানো আছে', en: 'Paused' },
  'radio.retry': { bn: 'স্ট্রিম পাওয়া যাচ্ছে না — {s} সেকেন্ডে আবার চেষ্টা (#{n})', en: 'Stream unreachable — retrying in {s}s (#{n})' },
  'radio.error': {
    bn: 'স্ট্রিম চালু হচ্ছে না। ভোরে সার্ভারে প্রচণ্ড ভিড় হয় — নিচের সরকারি বিকল্প চেষ্টা করুন।',
    en: 'The stream won’t start. Their servers get very busy at dawn — try the official options below.',
  },
  'radio.fallback': { bn: 'না চললে:', en: 'If it doesn’t play:' },
  'radio.fallbackSite': { bn: 'আকাশবাণীর সরকারি প্লেয়ার', en: 'Akashvani official player' },
  'radio.fallbackAndroid': { bn: 'NewsOnAir অ্যাপ (Android)', en: 'NewsOnAir app (Android)' },
  'radio.fallbackIos': { bn: 'NewsOnAir অ্যাপ (iPhone)', en: 'NewsOnAir app (iPhone)' },
  'radio.fallbackFm': {
    bn: 'অথবা সাধারণ রেডিও: আকাশবাণী কলকাতা ক ৬৫৭ kHz MW।',
    en: 'Or a regular radio set: Akashvani Kolkata A on 657 kHz MW.',
  },
  'radio.bg': {
    bn: 'স্ক্রিন বন্ধ করলেও অধিকাংশ ফোনে শোনা চলবে; লক-স্ক্রিন থেকেও থামানো/চালানো যাবে।',
    en: 'On most phones audio keeps playing with the screen off, and lock-screen controls work.',
  },
  'radio.listeners': { bn: '{n} জন এখন শুনছেন', en: '{n} listening now' },
  'vis.online': { bn: '{n} জন এখন অনলাইন', en: '{n} online now' },
  'vis.total': { bn: 'মোট {n} জন দেখেছেন', en: '{n} visitors so far' },
  'vis.label': { bn: 'ভিজিটর', en: 'Visitors' },

  // ── Wake ──
  'wake.title': { bn: 'মহালয়ার ভোরে জাগিয়ে দাও', en: 'Wake me for Mahalaya' },
  'wake.desc': {
    bn: 'আগের রাতে চালু করে রাখুন — ভোর ৩:৫০-এ (ভারতীয় সময়) রেডিও নিজে থেকেই বেজে উঠবে।',
    en: 'Switch this on the night before — the radio starts by itself at 3:50 AM IST.',
  },
  'wake.arm': { bn: 'চালু করুন', en: 'Turn on' },
  'wake.disarm': { bn: 'বন্ধ করুন', en: 'Turn off' },
  'wake.armed': { bn: 'চালু আছে — {t} তে বাজবে (আপনার সময়)', en: 'On — will play at {t} (your time)' },
  'wake.armedLock': { bn: 'স্ক্রিন জেগে থাকবে।', en: 'Screen will stay awake.' },
  'wake.noLock': {
    bn: 'এই ব্রাউজারে স্ক্রিন জাগিয়ে রাখা যায় না — ফোনের অটো-লক বন্ধ রাখুন।',
    en: 'This browser can’t keep the screen awake — turn off auto-lock on your phone.',
  },
  'wake.limits': {
    bn: 'সীমাবদ্ধতা: পাতাটি খোলা রাখতে হবে, ফোন চার্জে রাখুন আর সাইলেন্ট মোড/ভলিউম দেখে নিন। ফোন ঘুমিয়ে পড়লে বা ব্রাউজার বন্ধ হলে বাজবে না — ভরসার জন্য নিচের ক্যালেন্ডার রিমাইন্ডারও দিয়ে রাখুন।',
    en: 'Limits: this page must stay open, keep the phone on charge, and check silent mode/volume. If the phone sleeps or the browser is closed it can’t play — add the calendar reminder below as a backup.',
  },
  'wake.started': { bn: 'সময় হয়েছে — রেডিও চালু করা হল।', en: 'It’s time — radio started.' },
  'wake.past': { bn: 'এ বছরের সম্প্রচার শেষ হয়ে গেছে।', en: 'This year’s broadcast is over.' },

  // ── Reminders ──
  'rem.title': { bn: 'রিমাইন্ডার রাখুন', en: 'Set a reminder' },
  'rem.gcal': { bn: 'গুগল ক্যালেন্ডারে যোগ করুন', en: 'Add to Google Calendar' },
  'rem.ics': { bn: '.ics ফাইল (iPhone/Outlook)', en: '.ics file (iPhone/Outlook)' },
  'rem.shashthi': { bn: 'মহাষষ্ঠীর রিমাইন্ডারও', en: 'Also remind me for Shashthi' },
  'rem.wa': { bn: 'হোয়াটসঅ্যাপে শেয়ার করুন', en: 'Share on WhatsApp' },
  'rem.waText': {
    bn: 'শুভ মহালয়া 🙏 ১০ অক্টোবর ভোর ৩:৫০ থেকে আকাশবাণীতে মহিষাসুরমর্দিনী। এখান থেকে সরাসরি শুনুন, রিমাইন্ডারও দিয়ে রাখুন: {url}',
    en: 'Shubho Mahalaya 🙏 Mahishasuramardini on Akashvani from 3:50 AM IST, 10 Oct. Listen live and set a reminder here: {url}',
  },
  'rem.copy': { bn: 'লিংক কপি', en: 'Copy link' },
  'rem.copied': { bn: 'কপি হয়েছে', en: 'Copied' },
  'ev.mahalaya.title': { bn: 'মহালয়া — মহিষাসুরমর্দিনী লাইভ', en: 'Mahalaya — Mahishasuramardini live' },
  'ev.mahalaya.desc': {
    bn: 'ভোর ৩:৫০ (ভারতীয় সময়) থেকে আকাশবাণী কলকাতার সম্প্রচার। শুনুন: {url}',
    en: 'Akashvani Kolkata transmission from 3:50 AM IST. Listen: {url}',
  },
  'ev.shashthi.title': { bn: 'মহাষষ্ঠী — দুর্গাপুজো শুরু', en: 'Maha Shashthi — Durga Puja begins' },
  'ev.shashthi.desc': { bn: 'প্যান্ডেল ম্যাপ ও পুজোর গান: {url}', en: 'Pandal map & Puja songs: {url}' },

  // ── Schedule ──
  'sch.title': { bn: 'পুজোর নির্ঘণ্ট ২০২৬', en: 'Puja calendar 2026' },
  'sch.today': { bn: 'আজ', en: 'Today' },
  'sch.tomorrow': { bn: 'আগামীকাল', en: 'Tomorrow' },
  'sch.inDays': { bn: '{n} দিন পরে', en: 'In {n} days' },
  'sch.done': { bn: 'হয়ে গেছে', en: 'Done' },
  'sch.note': {
    bn: 'তারিখ বিশুদ্ধ সিদ্ধান্ত পঞ্জিকা অনুযায়ী (এ বছর সপ্তমী দুদিন)। গুপ্তপ্রেস পঞ্জিকায় অষ্টমী থেকে এক দিন আগে।',
    en: 'Dates follow the Bisuddha Siddhanta panjika (Saptami spans two days this year). Gupta Press panjika runs one day earlier from Ashtami.',
  },

  // ── Dhak ──
  'dhak.title': { bn: 'ঢাক বাজান', en: 'Play the dhak' },
  'dhak.hint': { bn: 'ঢাকে টোকা দিন (বা স্পেস/এন্টার চাপুন)', en: 'Tap the drum (or press Space/Enter)' },
  'dhak.label': { bn: 'ঢাক — বাজাতে চাপুন', en: 'Dhak — press to play' },
  'dhak.rhythm': { bn: 'পুরো বোল বাজাও', en: 'Play a full rhythm' },
  'dhak.stop': { bn: 'থামাও', en: 'Stop' },
  'dhak.credit': {
    bn: 'ঢাকের রেকর্ডিং: <a href="https://commons.wikimedia.org/wiki/File:Durga_Puja_Dhak_Dhol.ogg" target="_blank" rel="noopener">Mamta Jagdish Dhody</a>, উইকিমিডিয়া কমন্স, <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC BY-SA 4.0</a> (ছোট অংশে কাটা)।',
    en: 'Dhak recording: <a href="https://commons.wikimedia.org/wiki/File:Durga_Puja_Dhak_Dhol.ogg" target="_blank" rel="noopener">Mamta Jagdish Dhody</a>, Wikimedia Commons, <a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC BY-SA 4.0</a> (cut into short clips).',
  },
  'dhak.by': { bn: 'ঢাক সৌজন্যে', en: 'Dhak presented by' },

  // ── Playlists ──
  'pl.title': { bn: 'গান ও রেকর্ডিং', en: 'Songs & recordings' },
  'pl.mahalaya-recordings': { bn: 'মহালয়ার রেকর্ডিং', en: 'Mahalaya recordings' },
  'pl.mahalaya-songs': { bn: 'মহালয়ার গান', en: 'Mahalaya songs' },
  'pl.puja-songs': { bn: 'পুজোর গান', en: 'Durga Puja songs' },
  'pl.load': { bn: 'চালান', en: 'Load player' },
  'pl.audio': { bn: 'অডিও', en: 'Audio' },
  'pl.video': { bn: 'ভিডিও', en: 'Video' },
  'pl.nowPlaying': { bn: 'এখন বাজছে', en: 'Now playing' },
  'pl.open': { bn: 'অ্যাপে খুলুন', en: 'Open in app' },
  'pl.spotifyNote': {
    bn: '"অডিও" চাপলে ছোট প্লেয়ারে গান চলতে থাকবে, আপনি সাইটে ঘুরে বেড়াতে পারবেন (ইউটিউবের নিয়মে ছোট ভিডিও-জানলাটা দেখা যাবে)। স্পটিফাইতে লগ-ইন না থাকলে শুধু ৩০ সেকেন্ডের প্রিভিউ। সব প্লেয়ার সরকারি চ্যানেলের।',
    en: '“Audio” keeps the song playing in a small player while you browse (YouTube requires its small video window to stay visible). Spotify plays 30-second previews unless you’re logged in. All players are official channel embeds.',
  },
  'pl.empty': { bn: 'তালিকা তৈরি হচ্ছে…', en: 'List coming soon…' },

  // ── FAQ ──
  'faq.title': { bn: 'প্রশ্নোত্তর', en: 'FAQ' },
  'faq.q1': { bn: '২০২৬ সালে মহালয়া কবে?', en: 'When is Mahalaya in 2026?' },
  'faq.a1': {
    bn: 'শনিবার, ১০ অক্টোবর ২০২৬। আকাশবাণীতে মহিষাসুরমর্দিনীর সম্প্রচার ভোর ৩:৫০ থেকে ৫:৪৫ (ভারতীয় সময়)।',
    en: 'Saturday, 10 October 2026. Akashvani’s Mahishasuramardini transmission runs from 3:50 to 5:45 AM IST.',
  },
  'faq.q2': { bn: 'মহালয়া লাইভ রেডিও অনলাইনে কীভাবে শুনব?', en: 'How do I listen to Mahalaya live radio online?' },
  'faq.a2': {
    bn: 'এই পাতার প্লেয়ারে "শুনুন" চাপুন — এটি আকাশবাণী কলকাতার সরকারি স্ট্রিম চালায়। না চললে আকাশবাণীর ওয়েবসাইট বা NewsOnAir অ্যাপ ব্যবহার করুন, অথবা MW ৬৫৭ kHz-এ রেডিও ধরুন।',
    en: 'Press Play in the player on this page — it plays Akashvani Kolkata’s official stream. If it fails, use the Akashvani website or the NewsOnAir app, or tune a radio to 657 kHz MW.',
  },
  'faq.q3': { bn: 'দুর্গাপুজো ২০২৬-এর তারিখ কী?', en: 'What are the Durga Puja 2026 dates?' },
  'faq.a3': {
    bn: 'ষষ্ঠী ১৬ অক্টোবর, সপ্তমী ১৭–১৮ অক্টোবর, অষ্টমী ১৯ অক্টোবর, নবমী ২০ অক্টোবর, বিজয়া দশমী ২১ অক্টোবর (বিশুদ্ধ সিদ্ধান্ত পঞ্জিকা)।',
    en: 'Shashthi 16 Oct, Saptami 17–18 Oct, Ashtami 19 Oct, Nabami 20 Oct, Bijoya Dashami 21 Oct (Bisuddha Siddhanta panjika).',
  },
  'faq.q4': { bn: 'বিদেশ থেকে কখন শুনব?', en: 'What time is it outside India?' },
  'faq.a4': {
    bn: 'উপরের কাউন্টডাউন আপনার নিজের সময়েও দেখায়। যেমন লন্ডনে ৯ অক্টোবর রাত ১১:২০, নিউ ইয়র্কে সন্ধ্যা ৬:২০, দুবাইতে রাত ২:২০ (১০ অক্টোবর)।',
    en: 'The countdown above also shows your local time. For example: London 11:20 PM on 9 Oct, New York 6:20 PM on 9 Oct, Dubai 2:20 AM on 10 Oct.',
  },

  // ── Pandal map ──
  'pm.title': { bn: 'প্যান্ডেল ম্যাপ ২০২৬', en: 'Pandal map 2026' },
  'pm.intro': {
    bn: 'উত্তর ও দক্ষিণ কলকাতার পরিচিত পুজো — ম্যাপে দেখুন, খুঁজুন, আর এক চাপে গুগল ম্যাপসে রাস্তা পান।',
    en: 'Well-known pujas of North and South Kolkata — browse the map, search, and get Google Maps directions in one tap.',
  },
  'pm.listTitle': { bn: 'প্যান্ডেলের তালিকা', en: 'Pandal list' },
  'pm.all': { bn: 'সব', en: 'All' },
  'pm.zone.North Kolkata': { bn: 'উত্তর কলকাতা', en: 'North Kolkata' },
  'pm.zone.South Kolkata': { bn: 'দক্ষিণ কলকাতা', en: 'South Kolkata' },
  'pm.zone.Central': { bn: 'মধ্য কলকাতা', en: 'Central' },
  'pm.zone.Salt Lake–New Town': { bn: 'সল্টলেক–নিউ টাউন', en: 'Salt Lake–New Town' },
  'pm.zone.North 24 Parganas': { bn: 'উত্তর ২৪ পরগনা', en: 'North 24 Parganas' },
  'pm.search': { bn: 'প্যান্ডেল বা এলাকা খুঁজুন', en: 'Search pandal or area' },
  'pm.nearMe': { bn: 'আমার কাছে', en: 'Near me' },
  'pm.locating': { bn: 'আপনার অবস্থান খোঁজা হচ্ছে…', en: 'Finding your location…' },
  'pm.denied': {
    bn: 'অবস্থান পাওয়া গেল না (অনুমতি দেওয়া হয়নি বা বন্ধ আছে)। এলাকা দিয়ে খুঁজে নিন।',
    en: 'Couldn’t get your location (permission denied or unavailable). Search by area instead.',
  },
  'pm.sortedNear': { bn: 'কাছের প্যান্ডেল আগে দেখানো হচ্ছে', en: 'Showing nearest pandals first' },
  'pm.count': { bn: '{n}টি প্যান্ডেল', en: '{n} pandals' },
  'pm.none': { bn: 'কিছু পাওয়া গেল না।', en: 'No pandals found.' },
  'pm.showMap': { bn: 'ম্যাপ', en: 'Map' },
  'pm.showList': { bn: 'তালিকা', en: 'List' },
  'pm.loadingMap': { bn: 'ম্যাপ লোড হচ্ছে…', en: 'Loading map…' },
  'pm.directions': { bn: 'রাস্তা দেখুন', en: 'Directions' },
  'pm.walk': { bn: 'হেঁটে', en: 'Walk' },
  'pm.drive': { bn: 'গাড়িতে', en: 'Drive' },
  'pm.transit': { bn: 'বাস/মেট্রো', en: 'Transit' },
  'pm.onMap': { bn: 'ম্যাপে দেখুন', en: 'Show on map' },
  'pm.metro': { bn: 'কাছের মেট্রো', en: 'Nearest metro' },
  'pm.approx': { bn: 'অবস্থান আনুমানিক', en: 'Approximate location' },
  'pm.approxHelp': {
    bn: 'এই পিনটি প্যান্ডেলের ঠিক জায়গা কিনা নিশ্চিত নয় — কাছে গিয়ে স্থানীয়দের জিজ্ঞেস করুন।',
    en: 'This pin may not be the exact pandal spot — ask locally when you’re close.',
  },
  'pm.away': { bn: '{d} কিমি দূরে', en: '{d} km away' },
  'pm.eatNearby': { bn: 'কাছেই খাবার', en: 'Eat nearby' },
  'pm.eatCta': { bn: 'কাছেই আপনার দোকান? এখানে বিজ্ঞাপন দিন — {price}', en: 'Your shop nearby? Advertise here — {price}' },
  'pm.partner': { bn: 'প্যান্ডেল ম্যাপ পার্টনার', en: 'Pandal map partner' },
  'pm.routes': { bn: 'প্যান্ডেল হপিং রুট', en: 'Pandal-hopping routes' },
  'pm.routesNote': {
    bn: 'মোবাইলে গুগল ম্যাপস একসাথে সর্বোচ্চ ৫টি স্টপ খোলে, তাই বড় রুট দুই ভাগে।',
    en: 'On phones Google Maps opens at most 5 stops at once, so longer routes come in two parts.',
  },
  'pm.start': { bn: 'রুট শুরু করুন', en: 'Start route' },
  'pm.part': { bn: 'ভাগ {n}', en: 'Part {n}' },
  'pm.stops': { bn: '{n}টি স্টপ', en: '{n} stops' },
  'pm.suggest': { bn: 'নতুন প্যান্ডেল জানান / ভুল লোকেশন রিপোর্ট করুন', en: 'Suggest a pandal / report a wrong location' },
  'pm.suggestText': {
    bn: 'নমস্কার, {site} প্যান্ডেল ম্যাপ নিয়ে: (প্যান্ডেলের নাম, এলাকা, আর ঠিক লোকেশন/গুগল ম্যাপস লিংক লিখুন)',
    en: 'Hello, about the {site} pandal map: (pandal name, area, and the correct location / Google Maps link)',
  },
  'pm.dataNote': {
    bn: 'লোকেশন গুগল ম্যাপস থেকে একটি একটি করে মিলিয়ে দেখা। থিম ও সময় পুজো কমিটির ঘোষণা মিলিয়ে নিন।',
    en: 'Locations were checked one by one on Google Maps. Confirm themes and timings with the puja committees.',
  },

  // ── Advertise page ──
  'ad.waText': {
    bn: 'নমস্কার, আমি {site}-এ বিজ্ঞাপন দিতে চাই। স্লট: ',
    en: 'Hello, I would like to advertise on {site}. Slot: ',
  },
  'ad.taken': { bn: 'বুকড', en: 'Booked' },
  'bk.title': { bn: 'স্লট বুক করুন', en: 'Book a slot' },
  'bk.sendWa': { bn: 'হোয়াটসঅ্যাপে পাঠান', en: 'Send request on WhatsApp' },
  'bk.waHead': { bn: 'বিজ্ঞাপনের অনুরোধ — {site}', en: 'Ad booking request — {site}' },
  'bk.waSent': {
    bn: 'আপনার তথ্য হোয়াটসঅ্যাপে পাঠানো হয়েছে। আমরা নিশ্চিত করে পেমেন্টের লিংক পাঠাব।',
    en: 'Your details were sent on WhatsApp. We’ll confirm and send you the payment link.',
  },
  'bk.end': { bn: 'কবে পর্যন্ত চলবে *', en: 'Runs until *' },
  'bk.takenDates': { bn: 'এই দিনগুলো আগেই বুক হয়ে গেছে', en: 'Already booked on these dates' },
  'bk.pandalTakenDates': { bn: 'বাছাই করা কোনো প্যান্ডেল এই দিনগুলোয় বুক হয়ে আছে', en: 'A chosen pandal is already booked on these dates' },
  'bk.bookedDates': { bn: 'বুক হয়ে থাকা দিন', en: 'Booked dates' },
  'bk.days': { bn: 'দিন', en: 'days' },
  'bk.total': { bn: 'মোট', en: 'Total' },
  'bk.pickDates': { bn: 'তারিখ বেছে নিন — দাম এখানে দেখাবে', en: 'Pick dates — the price will show here' },
  'bk.wholePuja': { bn: 'পুরো পুজো', en: 'Whole puja' },
  'bk.reserved': { bn: 'সংরক্ষিত', en: 'reserved' },
  'bk.reservedDates': { bn: 'এই দিনগুলো এখন অন্য কেউ পেমেন্ট করছেন (সংরক্ষিত)।', en: 'Someone is paying for these dates right now (reserved).' },
  'bk.tryAgain': { bn: 'কয়েক মিনিট পরে আবার দেখুন ({n} মিনিট)', en: 'try again in about {n} min, or pick other dates' },
  'bk.step1': { bn: 'তথ্য দিন', en: 'Add your details' },
  'bk.step2': { bn: 'Razorpay-তে পেমেন্ট', en: 'Pay with Razorpay' },
  'bk.step3': { bn: '২৪ ঘণ্টায় যাচাই করে চালু · না চালালে পুরো টাকা ফেরত', en: 'Live within 24 h after review · full refund if not run' },
  'bk.unavailable': { bn: 'দুঃখিত, এই স্লট এইমাত্র বুক হয়ে গেছে।', en: 'Sorry, this slot was just booked.' },
  'bk.waBook': { bn: 'অনলাইন পেমেন্ট শীঘ্রই চালু হবে — এখন হোয়াটসঅ্যাপে বুক করুন।', en: 'Online payment is coming soon — book on WhatsApp for now.' },
  'bk.business': { bn: 'ব্যবসার তথ্য', en: 'About your business' },
  'bk.name': { bn: 'ব্যবসার নাম (ইংরেজিতে) *', en: 'Business name (English) *' },
  'bk.nameBn': { bn: 'ব্যবসার নাম (বাংলায়)', en: 'Business name (Bengali)' },
  'bk.tagline': { bn: 'এক লাইনে পরিচয় (ইংরেজিতে) *', en: 'One-line tagline (English) *' },
  'bk.taglinePh': { bn: 'যেমন: Fresh rosogolla since 1952', en: 'e.g. Fresh rosogolla since 1952' },
  'bk.taglineBn': { bn: 'এক লাইনে পরিচয় (বাংলায়)', en: 'One-line tagline (Bengali)' },
  'bk.desc': { bn: 'ব্যবসা সম্পর্কে আরও কিছু', en: 'More about your business' },
  'bk.descHint': { bn: 'স্পটলাইট কার্ডে দেখানো হয়; বাকি স্লটে আমাদের যাচাইয়ের জন্য।', en: 'Shown on the Spotlight card; for other slots it helps our review.' },
  'bk.logo': { bn: 'লোগো (PNG / JPG / WebP, ৩০০ KB পর্যন্ত)', en: 'Logo (PNG / JPG / WebP, up to 300 KB)' },
  'bk.where': { bn: 'কোথায় পাওয়া যাবে', en: 'Where to find you' },
  'bk.website': { bn: 'ওয়েবসাইট / ফেসবুক / ইনস্টাগ্রাম লিংক', en: 'Website / Facebook / Instagram link' },
  'bk.address': { bn: 'দোকানের ঠিকানা', en: 'Shop address' },
  'bk.maps': { bn: 'গুগল ম্যাপস লিংক', en: 'Google Maps link' },
  'bk.pandals': { bn: 'কোন প্যান্ডেলের কাছে? (সর্বোচ্চ ৩টি) *', en: 'Near which pandals? (up to 3) *' },
  'bk.contact': { bn: 'যোগাযোগ (শুধু আমাদের জন্য — হোয়াটসঅ্যাপ নম্বর ছাড়া সাইটে দেখানো হবে না)', en: 'Contact (for us only — nothing here is shown on the site except the WhatsApp number)' },
  'bk.person': { bn: 'আপনার নাম *', en: 'Your name *' },
  'bk.phone': { bn: 'মোবাইল নম্বর *', en: 'Mobile number *' },
  'bk.whatsapp': { bn: 'হোয়াটসঅ্যাপ নম্বর (বিজ্ঞাপনে "চ্যাট" বোতামের জন্য)', en: 'WhatsApp number (for a “chat” button on your ad)' },
  'bk.email': { bn: 'ইমেল (রসিদের জন্য)', en: 'Email (for the receipt)' },
  'bk.start': { bn: 'কবে থেকে চালু হবে', en: 'Start date' },
  'bk.startHint': { bn: 'যেকোনো দিন বেছে নিন — ২১ অক্টোবর (বিজয়া দশমী) পর্যন্ত। যে দিনগুলো আগে থেকে বুক করা, সেগুলো দেখানো হবে।', en: 'Pick any dates up to 21 October (Bijoya Dashami). Dates already booked are shown below.' },
  'bk.consent': {
    bn: 'আমি নিশ্চিত করছি যে এই ব্যবসা ও লোগো আমার/আমাদের। বিজ্ঞাপনে "স্পনসর" লেখা থাকবে, চালুর আগে যাচাই করা হবে, না চালালে পুরো টাকা ফেরত। <a href="/policies/" target="_blank">শর্তাবলি</a> মেনে নিচ্ছি।',
    en: 'I confirm this business and logo are mine/ours. The ad will be labelled “Sponsored”, reviewed before it goes live, and fully refunded if not run. I accept the <a href="/policies/" target="_blank">terms</a>.',
  },
  'bk.pay': { bn: '{price} পেমেন্ট করুন', en: 'Pay {price}' },
  'bk.paying': { bn: 'অপেক্ষা করুন…', en: 'Please wait…' },
  'bk.secure': {
    bn: 'পেমেন্ট হয় Razorpay-তে (UPI, কার্ড, নেটব্যাংকিং, ওয়ালেট)। আপনার কার্ড বা UPI তথ্য আমরা কখনো দেখি না।',
    en: 'Payment happens on Razorpay (UPI, card, netbanking, wallet). We never see your card or UPI details.',
  },
  'bk.mockText': { bn: 'Razorpay কী এখনো যোগ করা হয়নি — এটা পরীক্ষার পেমেন্ট, আসল টাকা কাটবে না।', en: 'Razorpay keys aren’t added yet — this is a test payment; no real money moves.' },
  'bk.mockPay': { bn: 'পরীক্ষামূলক পেমেন্ট {price}', en: 'Test payment {price}' },
  'bk.cancel': { bn: 'বাতিল', en: 'Cancel' },
  'bk.dismissed': {
    bn: 'পেমেন্ট সম্পূর্ণ হয়নি। স্লটটি ১৫ মিনিট আপনার জন্য রাখা আছে — আবার চেষ্টা করুন।',
    en: 'Payment wasn’t completed. The slot is held for you for 15 minutes — try again.',
  },
  'bk.doneTitle': { bn: 'পেমেন্ট সফল — ধন্যবাদ!', en: 'Payment received — thank you!' },
  'bk.doneText': {
    bn: 'আপনার বিজ্ঞাপন এখন যাচাইয়ের অপেক্ষায়। ২৪ ঘণ্টার মধ্যে চালু হলে হোয়াটসঅ্যাপে জানাব। কোনো কারণে চালাতে না পারলে পুরো টাকা ফেরত।',
    en: 'Your ad is now waiting for review. We’ll WhatsApp you when it’s live, within 24 hours. If we can’t run it, you’ll get a full refund.',
  },
  'bk.ref': { bn: 'বুকিং নম্বর', en: 'Booking reference' },
  'bk.doneWa': { bn: 'হোয়াটসঅ্যাপে জানান', en: 'Tell us on WhatsApp' },
  'bk.doneWaText': { bn: 'নমস্কার, আমি {site}-এ বিজ্ঞাপনের পেমেন্ট করেছি। বুকিং নম্বর: {ref} ({business})', en: 'Hello, I have paid for an ad on {site}. Booking reference: {ref} ({business})' },
  'bk.err.required': { bn: 'এটা দিতে হবে', en: 'Required' },
  'bk.err.length': { bn: 'দৈর্ঘ্য ঠিক নেই', en: 'Too short or too long' },
  'bk.err.invalid': { bn: 'ঠিক নেই — একবার দেখে নিন', en: 'Doesn’t look right — please check' },
  'bk.err.too_large': { bn: 'ফাইল ৩০০ KB-এর বেশি', en: 'File is larger than 300 KB' },
  'bk.err.bad_type': { bn: 'শুধু PNG, JPG বা WebP ছবি', en: 'Only PNG, JPG or WebP images' },
  'bk.err.form': { bn: 'কয়েকটি ঘর ঠিক করে আবার চেষ্টা করুন।', en: 'Please fix the highlighted fields and try again.' },
  'bk.err.slot_taken': { bn: 'দুঃখিত, এই স্লট এইমাত্র বুক হয়ে গেছে।', en: 'Sorry, this slot was just booked.' },
  'bk.err.pandal_taken': { bn: 'বাছাই করা কোনো প্যান্ডেলে ইতিমধ্যে বিজ্ঞাপন আছে — অন্য প্যান্ডেল বাছুন।', en: 'One of the chosen pandals already has an ad — pick another.' },
  'bk.err.rate_limited': { bn: 'অনেকবার চেষ্টা হয়েছে — একটু পরে আবার চেষ্টা করুন।', en: 'Too many attempts — please try again a little later.' },
  'bk.err.payments_not_configured': { bn: 'অনলাইন পেমেন্ট এখনো চালু হয়নি — হোয়াটসঅ্যাপে বুক করুন।', en: 'Online payment isn’t switched on yet — please book on WhatsApp.' },
  'bk.err.generic': { bn: 'কিছু একটা গোলমাল হয়েছে। আবার চেষ্টা করুন বা হোয়াটসঅ্যাপে জানান।', en: 'Something went wrong. Please try again or message us on WhatsApp.' },
  'bk.err.verify': {
    bn: 'পেমেন্ট হয়েছে কিনা নিশ্চিত হতে পারিনি। টাকা কেটে থাকলে চিন্তা করবেন না — আমরা মিলিয়ে দেখব। বুকিং নম্বরসহ হোয়াটসঅ্যাপে জানান।',
    en: 'We couldn’t confirm the payment. If money was debited, don’t worry — we’ll reconcile it. Message us on WhatsApp with your booking reference.',
  },
  'slot.dhak': { bn: '"ঢাক সৌজন্যে …"', en: '“Dhak presented by …”' },
  'slot.dhak.where': { bn: 'হোম পেজে ঢাক বাজানোর অংশে', en: 'Under the dhak on the home page' },
  'slot.countdown': { bn: '"কাউন্টডাউন সৌজন্যে …"', en: '“Countdown by …”' },
  'slot.countdown.where': { bn: 'হোম পেজের কাউন্টডাউনের নিচে', en: 'Below the home-page countdown' },
  'slot.map-partner': { bn: 'প্যান্ডেল ম্যাপ পার্টনার', en: 'Pandal map partner' },
  'slot.map-partner.where': { bn: 'প্যান্ডেল ম্যাপের মাথায়', en: 'Top of the pandal map page' },
  'slot.pandal-nearby': { bn: '"কাছেই খাবার" — প্যান্ডেল কার্ডে', en: '“Eat nearby” on pandal cards' },
  'slot.pandal-nearby.where': {
    bn: 'আপনার দোকানের কাছের প্যান্ডেলগুলোর কার্ডে (প্রতি এলাকা)',
    en: 'On the cards of pandals near your shop (per area)',
  },
};
