/** All UI copy, Bengali + English. Keep keys grouped by page/feature. */
type Entry = { bn: string; en: string };
export const dict: Record<string, Entry> = {
  // ── Common chrome ──
  'nav.home': { bn: 'হোম', en: 'Home' },
  'nav.map': { bn: 'প্যান্ডেল ম্যাপ', en: 'Pandal map' },
  'nav.advertise': { bn: 'বিজ্ঞাপন দিন', en: 'Advertise' },
  'nav.policies': { bn: 'যোগাযোগ ও নীতি', en: 'Contact & policies' },
  'skip': { bn: 'মূল অংশে যান', en: 'Skip to content' },
  'sponsored': { bn: 'স্পনসর', en: 'Sponsored' },
  'adhere.cta': { bn: 'এখানে আপনার বিজ্ঞাপন — {price} থেকে · বুক করুন', en: 'Your brand here — from {price} · Book now' },

  // ── Hero / countdown ──
  'hero.title.durga': { bn: 'শুভ দুর্গাপুজো', en: 'Happy Durga Puja' },
  'hero.kicker.puja': { bn: 'দুর্গাপুজো ২০২৬ · ১৬–২১ অক্টোবর', en: 'Durga Puja 2026 · 16–21 October' },
  'hero.title.puja': { bn: 'শুভ শারদীয়া', en: 'Shubho Sharodiya' },
  'hero.sub.puja': { bn: 'কলকাতা আর বিভিন্ন জেলার ৬০টির বেশি পুজো এক ম্যাপে — কাছের প্যান্ডেল, মেট্রো আর হেঁটে ঘোরার রুট দেখে ঠাকুর দেখতে বেরিয়ে পড়ুন।', en: '60+ pujas in Kolkata and beyond on one map — find the pandals near you, the metro and a walking route, and head out pandal-hopping.' },
  'hero.all': { bn: 'সব প্যান্ডেল দেখুন', en: 'All pandals' },
  'hero.kicker.bijoya': { bn: 'বিজয়া দশমী ২০২৬', en: 'Bijoya Dashami 2026' },
  'hero.title.bijoya': { bn: 'শুভ বিজয়া', en: 'Shubho Bijoya' },
  'hero.sub.bijoya': { bn: 'আসছে বছর আবার হবে। মহালয়ার রেকর্ডিং আর পুজোর গান নিচে রইল।', en: 'Until next year. Mahalaya recordings and Puja songs are below.' },
  'cd.by': { bn: 'মতামত সৌজন্যে', en: 'Poll by' },

  'ui.close': { bn: 'বন্ধ করুন', en: 'Close' },
  'dock.label': { bn: 'আরও', en: 'More' },
  'dock.schedule': { bn: 'নির্ঘণ্ট', en: 'Schedule' },
  'dock.faq': { bn: 'প্রশ্নোত্তর', en: 'FAQ' },
  'dock.card': { bn: 'শুভেচ্ছা কার্ড', en: 'Greeting card' },
  'rem.waShort': { bn: 'হোয়াটসঅ্যাপ', en: 'WhatsApp' },
  'share.native': { bn: 'শেয়ার', en: 'Share' },
  'share.group': { bn: 'শেয়ার করুন', en: 'Share' },
  'share.title': { bn: 'দুর্গাপুজো ২০২৬ প্যান্ডেল ম্যাপ — মা আসছেন', en: 'Durga Puja 2026 pandal map — Ma Aschen' },
  'share.text': { bn: 'শুভ দুর্গাপুজো 🙏 কাছের প্যান্ডেল, মেট্রো আর হাঁটার রুট এক ম্যাপে।', en: 'Happy Durga Puja 🙏 Nearby pandals, metro and walking routes on one map.' },
  'share.fb': { bn: 'ফেসবুক', en: 'Facebook' },
  'share.copy': { bn: 'লিংক কপি', en: 'Copy link' },
  'share.copied': { bn: 'কপি হয়েছে ✓', en: 'Copied ✓' },
  'slot.spotlight': { bn: 'স্পটলাইট কার্ড', en: 'Spotlight card' },
  'slot.spotlight.where': { bn: 'হোম পেজের ছবির উপর, ডান দিকে (রেডিও প্লেয়ার থেকে দূরে)', en: 'On the home hero image, right side (away from the radio player)' },
  // ── Visitors ──
  'radio.listeners': { bn: '{n} জন এখন শুনছেন', en: '{n} listening now' },
  'vis.online': { bn: '{n} জন এখন অনলাইন', en: '{n} online now' },
  'vis.total': { bn: 'মোট {n} জন দেখেছেন', en: '{n} visitors so far' },
  'vis.label': { bn: 'ভিজিটর', en: 'Visitors' },

  // ── Share ──
  'rem.waText': { bn: 'শুভ দুর্গাপুজো 🙏 কলকাতা আর জেলার ৬০টির বেশি পুজো এক ম্যাপে — আপনার কাছের প্যান্ডেল, মেট্রো আর হাঁটার রুট: {url}', en: 'Happy Durga Puja 🙏 60+ pujas in Kolkata and beyond on one map — pandals near you, the metro and a walking route: {url}' },

  // ── Schedule ──
  'sch.title': { bn: 'পুজোর নির্ঘণ্ট ২০২৬', en: 'Puja calendar 2026' },
  'sch.today': { bn: 'আজ', en: 'Today' },
  'sch.tomorrow': { bn: 'আগামীকাল', en: 'Tomorrow' },
  'sch.inDays': { bn: '{n} দিন পরে', en: 'In {n} days' },
  'sch.done': { bn: 'হয়ে গেছে', en: 'Done' },
  'sch.note': {
    bn: 'তারিখ বিশুদ্ধ সিদ্ধান্ত পঞ্জিকা অনুযায়ী (এ বছর সপ্তমী দুদিন)। গুপ্তপ্রেস পঞ্জিকায় অষ্টমী থেকে এক দিন আগে।',
    en: 'Dates follow the Bisuddha Siddhanta panjika (Saptami spans two days this year). Gupta Press panjika runs one day earlier from Ashtami.',
  },

  // ── FAQ ──
  'faq.title': { bn: 'প্রশ্নোত্তর', en: 'FAQ' },
  'faq.q1': { bn: 'দুর্গাপুজো ২০২৬-এর তারিখ কী?', en: 'What are the Durga Puja 2026 dates?' },
  'faq.a1': { bn: 'ষষ্ঠী ১৬ অক্টোবর, সপ্তমী ১৭–১৮ অক্টোবর, অষ্টমী ১৯ অক্টোবর, নবমী ২০ অক্টোবর, বিজয়া দশমী ২১ অক্টোবর (বিশুদ্ধ সিদ্ধান্ত পঞ্জিকা)।', en: 'Shashthi 16 Oct, Saptami 17–18 Oct, Ashtami 19 Oct, Nabami 20 Oct, Bijoya Dashami 21 Oct (Bisuddha Siddhanta panjika).' },
  'faq.q2': { bn: 'প্যান্ডেল ম্যাপ কীভাবে ব্যবহার করব?', en: 'How do I use the pandal map?' },
  'faq.a2': { bn: '“আমার কাছের প্যান্ডেল” চাপুন — কাছের পুজো আগে দেখাবে, দূরত্বসহ। প্রতিটি প্যান্ডেলের সঙ্গে কাছের মেট্রো আর এক চাপে গুগল ম্যাপস ডিরেকশন আছে।', en: 'Tap “Pandals near me” to list the closest pujas first, with distances. Each pandal shows the nearest metro and one-tap Google Maps directions.' },
  'faq.q3': { bn: 'প্যান্ডেল হপিংয়ের রুট পাব?', en: 'Can I get a pandal-hopping route?' },
  'faq.a3': { bn: 'হ্যাঁ। “আমার কাছের প্যান্ডেল” চাপলে আপনার জায়গা থেকে ৫ কিমির মধ্যের প্যান্ডেলগুলো হাঁটার সুবিধামতো পরপর সাজিয়ে গুগল ম্যাপসে রুট খোলে।', en: 'Yes. Tap “Pandals near me” and the pandals within 5 km of you are put in an easy walking order, ready to open as a Google Maps route.' },
  'faq.q4': { bn: 'কলকাতার বাইরের পুজোও আছে?', en: 'Does it cover pujas outside Kolkata?' },
  'faq.a4': { bn: 'হ্যাঁ — উত্তর ও দক্ষিণ ২৪ পরগনা, হাওড়া, হুগলি, নদিয়া, বাঁকুড়া, শিলিগুড়ি, জলপাইগুড়ি আর কোচবিহারের পরিচিত পুজোও ম্যাপে আছে।', en: 'Yes — well-known pujas in North and South 24 Parganas, Howrah, Hooghly, Nadia, Bankura, Siliguri, Jalpaiguri and Cooch Behar are on the map too.' },

  // ── Greeting card ──
  'card.open': { bn: 'শুভেচ্ছা কার্ড বানান', en: 'Make a greeting card' },
  'card.title': { bn: 'পুজোর শুভেচ্ছা কার্ড', en: 'Durga Puja greeting card' },
  'card.name': { bn: 'আপনার নাম (ইচ্ছে হলে)', en: 'Your name (optional)' },
  'card.greet': { bn: 'শুভ দুর্গাপুজো', en: 'Happy Durga Puja' },
  'card.from': { bn: '{name}-এর পক্ষ থেকে', en: 'from {name}' },
  'card.date': { bn: 'দুর্গাপুজো ২০২৬ · ১৬–২১ অক্টোবর', en: 'Durga Puja 2026 · 16–21 October' },
  'card.listen': { bn: 'প্যান্ডেল ম্যাপ দেখে ঠাকুর দেখুন', en: 'Find the pandals near you on the map' },
  'card.download': { bn: 'ছবি নামান', en: 'Download image' },
  'card.share': { bn: 'শেয়ার করুন', en: 'Share' },
  'card.hint': { bn: 'স্টোরি বা হোয়াটসঅ্যাপ স্ট্যাটাসে দিন। নামটি আপনার ফোনেই থাকে, কোথাও পাঠানো হয় না।', en: 'Post it to Stories or WhatsApp status. Your name stays on your device and is never sent anywhere.' },
  'card.shareText': { bn: 'শুভ দুর্গাপুজো 🙏 প্যান্ডেল ম্যাপ: {url}', en: 'Happy Durga Puja 🙏 Pandal map: {url}' },

  // ── Polls ──
  'poll.title': { bn: 'আপনার মত দিন', en: 'Tell us what you think' },
  'poll.use-for-hopping.q': { bn: 'এবার পুজোয় প্যান্ডেল ঘুরতে এই সাইট ব্যবহার করবেন?', en: 'Will you use this site for pandal hopping this Puja?' },
  'poll.use-for-hopping.yes': { bn: 'হ্যাঁ', en: 'Yes' },
  'poll.use-for-hopping.maybe': { bn: 'হয়তো', en: 'Maybe' },
  'poll.use-for-hopping.no': { bn: 'না', en: 'No' },
  'poll.more-pandals.q': { bn: 'ম্যাপে আরও প্যান্ডেল যোগ করব?', en: 'Should we add more pandals to the map?' },
  'poll.more-pandals.yes': { bn: 'হ্যাঁ, আরও চাই', en: 'Yes, add more' },
  'poll.more-pandals.no': { bn: 'না, এতেই হবে', en: 'No, this is enough' },
  'poll.tap': { bn: 'একটি উত্তরে চাপুন। ফলাফল ভোটের পরে দেখা যাবে।', en: 'Tap an answer. Results show after you vote.' },
  'poll.votes': { bn: 'মোট {n}টি ভোট · মত বদলাতে অন্য উত্তরে চাপুন', en: 'Total votes: {n} · tap another answer to change yours' },

  // ── Pandal map ──
  'pm.title': { bn: 'প্যান্ডেল ম্যাপ ২০২৬', en: 'Pandal map 2026' },
  'pm.intro': {
    bn: 'কলকাতা, দুই ২৪ পরগনা আর অন্যান্য জেলার পরিচিত পুজো — ম্যাপে দেখুন, খুঁজুন, আর এক চাপে গুগল ম্যাপসে রাস্তা পান।',
    en: 'Well-known pujas of Kolkata, the 24 Parganas and other districts — browse the map, search, and get Google Maps directions in one tap.',
  },
  'pm.listTitle': { bn: 'প্যান্ডেলের তালিকা', en: 'Pandal list' },
  'pm.all': { bn: 'সব', en: 'All' },
  'pm.zone.North Kolkata': { bn: 'উত্তর কলকাতা', en: 'North Kolkata' },
  'pm.zone.South Kolkata': { bn: 'দক্ষিণ কলকাতা', en: 'South Kolkata' },
  'pm.zone.Central': { bn: 'মধ্য কলকাতা', en: 'Central' },
  'pm.zone.Salt Lake–New Town': { bn: 'সল্টলেক–নিউ টাউন', en: 'Salt Lake–New Town' },
  'pm.zone.North 24 Parganas': { bn: 'উত্তর ২৪ পরগনা', en: 'North 24 Parganas' },
  'pm.zone.South 24 Parganas': { bn: 'দক্ষিণ ২৪ পরগনা', en: 'South 24 Parganas' },
  'pm.zone.Howrah': { bn: 'হাওড়া', en: 'Howrah' },
  'pm.zone.Hooghly': { bn: 'হুগলি', en: 'Hooghly' },
  'pm.zone.Nadia': { bn: 'নদিয়া', en: 'Nadia' },
  'pm.zone.Bankura': { bn: 'বাঁকুড়া', en: 'Bankura' },
  'pm.zone.Siliguri': { bn: 'শিলিগুড়ি', en: 'Siliguri' },
  'pm.zone.Jalpaiguri': { bn: 'জলপাইগুড়ি', en: 'Jalpaiguri' },
  'pm.zone.Cooch Behar': { bn: 'কোচবিহার', en: 'Cooch Behar' },
  'pm.zone.other': { bn: 'অন্যান্য জেলা', en: 'Other districts' },
  'pm.search': { bn: 'প্যান্ডেল বা এলাকা খুঁজুন', en: 'Search pandal or area' },
  'pm.nearMe': { bn: 'আমার কাছের প্যান্ডেল', en: 'Pandals near me' },
  'pm.areas': { bn: 'এলাকা', en: 'Areas' },
  'pm.you': { bn: 'আপনি এখানে', en: 'You are here' },
  'pm.inList': { bn: 'তালিকায়', en: 'In the list' },
  'pm.hop.title': { bn: 'আপনার প্যান্ডেল হপিং রুট', en: 'Your pandal-hopping route' },
  'pm.hop.lead': { bn: 'আপনার জায়গা থেকে {km} কিমির মধ্যে {n}টি প্যান্ডেল, হাঁটার সুবিধামতো পরপর সাজানো। গুগল ম্যাপস একবারে ৪টি প্যান্ডেল খোলে — একটা ভাগ শেষ হলে পরেরটা চাপুন।', en: '{n} pandals within {km} km of you, in an easy walking order. Google Maps opens 4 at a time — when you finish one part, tap the next.' },
  'pm.hop.start': { bn: 'রুট শুরু করুন ({n}টি প্যান্ডেল)', en: 'Start route ({n} pandals)' },
  'pm.hop.next': { bn: 'পরের ভাগ {n}', en: 'Next: part {n}' },
  'pm.hop.none': { bn: '{km} কিমির মধ্যে একাধিক প্যান্ডেল নেই, তাই হাঁটার রুট দেওয়া গেল না। নিচের তালিকা থেকে কাছের প্যান্ডেলের রাস্তা দেখুন।', en: 'There aren’t two or more pandals within {km} km, so there’s no walking route. Use the list below for directions to the nearest ones.' },
  'pm.locating': { bn: 'আপনার অবস্থান খোঁজা হচ্ছে…', en: 'Finding your location…' },
  'pm.denied': {
    bn: 'এই সাইটকে লোকেশন দেওয়া বন্ধ আছে। ব্রাউজারের ঠিকানার পাশের 🔒 চিহ্নে চেপে লোকেশন চালু করুন — অথবা ম্যাপে আপনার জায়গায় চাপুন।',
    en: 'Location is blocked for this site. Allow it from the 🔒 icon next to the address — or tap where you are on the map.',
  },
  'pm.unavailable': {
    bn: 'ফোন বা কম্পিউটার লোকেশন দিচ্ছে না। লোকেশন সার্ভিস চালু আছে কিনা দেখুন (ম্যাকে: System Settings › Privacy & Security › Location Services › আপনার ব্রাউজার)। ততক্ষণ ম্যাপে আপনার জায়গায় চাপুন।',
    en: 'Your device isn’t giving a location. Check that location services are on (on a Mac: System Settings › Privacy & Security › Location Services › your browser). Meanwhile, tap where you are on the map.',
  },
  'pm.timeout': {
    bn: 'লোকেশন পেতে বেশি সময় লাগছে। আবার চেষ্টা করুন, অথবা ম্যাপে আপনার জায়গায় চাপুন।',
    en: 'Getting your location is taking too long. Try again, or tap where you are on the map.',
  },
  'pm.pickHint': { bn: 'ম্যাপে আপনার জায়গায় চাপুন', en: 'Tap where you are on the map' },
  'pm.sortedNear': { bn: 'কাছের প্যান্ডেল আগে দেখানো হচ্ছে', en: 'Showing nearest pandals first' },
  'pm.count': { bn: '{n}টি প্যান্ডেল', en: '{n} pandals' },
  'pm.none': { bn: 'কিছু পাওয়া গেল না।', en: 'No pandals found.' },
  'pm.loadingMap': { bn: 'ম্যাপ লোড হচ্ছে…', en: 'Loading map…' },
  'pm.directions': { bn: 'রাস্তা দেখুন', en: 'Directions' },
  'pm.onMap': { bn: 'ম্যাপে দেখুন', en: 'Show on map' },
  'pm.metro': { bn: 'কাছের মেট্রো', en: 'Nearest metro' },
  'pm.approx': { bn: 'অবস্থান আনুমানিক', en: 'Approximate location' },
  'pm.approxHelp': {
    bn: 'এই পিনটি প্যান্ডেলের ঠিক জায়গা কিনা নিশ্চিত নয় — কাছে গিয়ে স্থানীয়দের জিজ্ঞেস করুন।',
    en: 'This pin may not be the exact pandal spot — ask locally when you’re close.',
  },
  'pm.away': { bn: '{d} কিমি দূরে', en: '{d} km away' },
  'pm.eatNearby': { bn: 'কাছেই খাবার', en: 'Eat nearby' },
  'pm.eatCta': { bn: 'কাছেই আপনার দোকান? এখানে বিজ্ঞাপন দিন — {price}', en: 'Your shop nearby? Advertise here — {price}' },
  'pm.partner': { bn: 'প্যান্ডেল ম্যাপ পার্টনার', en: 'Pandal map partner' },
  'pm.suggest': { bn: 'নতুন প্যান্ডেল জানান / ভুল লোকেশন রিপোর্ট করুন', en: 'Suggest a pandal / report a wrong location' },
  'pm.suggestText': {
    bn: 'নমস্কার, {site} প্যান্ডেল ম্যাপ নিয়ে: (প্যান্ডেলের নাম, এলাকা, আর ঠিক লোকেশন/গুগল ম্যাপস লিংক লিখুন)',
    en: 'Hello, about the {site} pandal map: (pandal name, area, and the correct location / Google Maps link)',
  },
  'pm.dataNote': {
    bn: 'লোকেশন গুগল ম্যাপস থেকে একটি একটি করে মিলিয়ে দেখা। থিম ও সময় পুজো কমিটির ঘোষণা মিলিয়ে নিন।',
    en: 'Locations were checked one by one on Google Maps. Confirm themes and timings with the puja committees.',
  },

  // ── Advertise page ──
  'ad.waText': {
    bn: 'নমস্কার, আমি {site}-এ বিজ্ঞাপন দিতে চাই। স্লট: ',
    en: 'Hello, I would like to advertise on {site}. Slot: ',
  },
  'ad.taken': { bn: 'বুকড', en: 'Booked' },
  'bk.title': { bn: 'স্লট বুক করুন', en: 'Book a slot' },
  'bk.sendWa': { bn: 'হোয়াটসঅ্যাপে পাঠান', en: 'Send request on WhatsApp' },
  'bk.waHead': { bn: 'বিজ্ঞাপনের অনুরোধ — {site}', en: 'Ad booking request — {site}' },
  'bk.waSent': {
    bn: 'আপনার তথ্য হোয়াটসঅ্যাপে পাঠানো হয়েছে। আমরা নিশ্চিত করে পেমেন্টের লিংক পাঠাব।',
    en: 'Your details were sent on WhatsApp. We’ll confirm and send you the payment link.',
  },
  'bk.end': { bn: 'কবে পর্যন্ত চলবে *', en: 'Runs until *' },
  'bk.takenDates': { bn: 'এই দিনগুলো আগেই বুক হয়ে গেছে', en: 'Already booked on these dates' },
  'bk.pandalTakenDates': { bn: 'বাছাই করা কোনো প্যান্ডেল এই দিনগুলোয় বুক হয়ে আছে', en: 'A chosen pandal is already booked on these dates' },
  'bk.bookedDates': { bn: 'বুক হয়ে থাকা দিন', en: 'Booked dates' },
  'bk.days': { bn: 'দিন', en: 'days' },
  'bk.total': { bn: 'মোট', en: 'Total' },
  'bk.pickDates': { bn: 'তারিখ বেছে নিন — দাম এখানে দেখাবে', en: 'Pick dates — the price will show here' },
  'bk.wholePuja': { bn: 'পুরো পুজো', en: 'Whole puja' },
  'bk.reserved': { bn: 'সংরক্ষিত', en: 'reserved' },
  'bk.reservedDates': { bn: 'এই দিনগুলো এখন অন্য কেউ পেমেন্ট করছেন (সংরক্ষিত)।', en: 'Someone is paying for these dates right now (reserved).' },
  'bk.tryAgain': { bn: 'কয়েক মিনিট পরে আবার দেখুন ({n} মিনিট)', en: 'try again in about {n} min, or pick other dates' },
  'bk.step1': { bn: 'তথ্য দিন', en: 'Add your details' },
  'bk.step2': { bn: 'Razorpay-তে পেমেন্ট', en: 'Pay with Razorpay' },
  'bk.step3': { bn: '২৪ ঘণ্টায় যাচাই করে চালু · না চালালে পুরো টাকা ফেরত', en: 'Live within 24 h after review · full refund if not run' },
  'bk.unavailable': { bn: 'দুঃখিত, এই স্লট এইমাত্র বুক হয়ে গেছে।', en: 'Sorry, this slot was just booked.' },
  'bk.waBook': { bn: 'অনলাইন পেমেন্ট শীঘ্রই চালু হবে — এখন হোয়াটসঅ্যাপে বুক করুন।', en: 'Online payment is coming soon — book on WhatsApp for now.' },
  'bk.business': { bn: 'ব্যবসার তথ্য', en: 'About your business' },
  'bk.name': { bn: 'ব্যবসার নাম (ইংরেজিতে) *', en: 'Business name (English) *' },
  'bk.nameBn': { bn: 'ব্যবসার নাম (বাংলায়)', en: 'Business name (Bengali)' },
  'bk.tagline': { bn: 'এক লাইনে পরিচয় (ইংরেজিতে) *', en: 'One-line tagline (English) *' },
  'bk.taglinePh': { bn: 'যেমন: Fresh rosogolla since 1952', en: 'e.g. Fresh rosogolla since 1952' },
  'bk.taglineBn': { bn: 'এক লাইনে পরিচয় (বাংলায়)', en: 'One-line tagline (Bengali)' },
  'bk.desc': { bn: 'ব্যবসা সম্পর্কে আরও কিছু', en: 'More about your business' },
  'bk.descHint': { bn: 'স্পটলাইট কার্ডে দেখানো হয়; বাকি স্লটে আমাদের যাচাইয়ের জন্য।', en: 'Shown on the Spotlight card; for other slots it helps our review.' },
  'bk.logo': { bn: 'লোগো (PNG / JPG / WebP, ৩০০ KB পর্যন্ত)', en: 'Logo (PNG / JPG / WebP, up to 300 KB)' },
  'bk.where': { bn: 'কোথায় পাওয়া যাবে', en: 'Where to find you' },
  'bk.website': { bn: 'ওয়েবসাইট / ফেসবুক / ইনস্টাগ্রাম লিংক', en: 'Website / Facebook / Instagram link' },
  'bk.address': { bn: 'দোকানের ঠিকানা', en: 'Shop address' },
  'bk.maps': { bn: 'গুগল ম্যাপস লিংক', en: 'Google Maps link' },
  'bk.pandals': { bn: 'কোন প্যান্ডেলের কাছে? (সর্বোচ্চ ৩টি) *', en: 'Near which pandals? (up to 3) *' },
  'bk.contact': { bn: 'যোগাযোগ (শুধু আমাদের জন্য — হোয়াটসঅ্যাপ নম্বর ছাড়া সাইটে দেখানো হবে না)', en: 'Contact (for us only — nothing here is shown on the site except the WhatsApp number)' },
  'bk.person': { bn: 'আপনার নাম *', en: 'Your name *' },
  'bk.phone': { bn: 'মোবাইল নম্বর *', en: 'Mobile number *' },
  'bk.whatsapp': { bn: 'হোয়াটসঅ্যাপ নম্বর (বিজ্ঞাপনে "চ্যাট" বোতামের জন্য)', en: 'WhatsApp number (for a “chat” button on your ad)' },
  'bk.email': { bn: 'ইমেল (রসিদের জন্য)', en: 'Email (for the receipt)' },
  'bk.start': { bn: 'কবে থেকে চালু হবে', en: 'Start date' },
  'bk.startHint': { bn: 'যেকোনো দিন বেছে নিন — ২১ অক্টোবর (বিজয়া দশমী) পর্যন্ত। যে দিনগুলো আগে থেকে বুক করা, সেগুলো দেখানো হবে।', en: 'Pick any dates up to 21 October (Bijoya Dashami). Dates already booked are shown below.' },
  'bk.consent': {
    bn: 'আমি নিশ্চিত করছি যে এই ব্যবসা ও লোগো আমার/আমাদের। বিজ্ঞাপনে "স্পনসর" লেখা থাকবে, চালুর আগে যাচাই করা হবে, না চালালে পুরো টাকা ফেরত। <a href="/policies/" target="_blank">শর্তাবলি</a> মেনে নিচ্ছি।',
    en: 'I confirm this business and logo are mine/ours. The ad will be labelled “Sponsored”, reviewed before it goes live, and fully refunded if not run. I accept the <a href="/policies/" target="_blank">terms</a>.',
  },
  'bk.pay': { bn: '{price} পেমেন্ট করুন', en: 'Pay {price}' },
  'bk.paying': { bn: 'অপেক্ষা করুন…', en: 'Please wait…' },
  'bk.secure': {
    bn: 'পেমেন্ট হয় Razorpay-তে (UPI, কার্ড, নেটব্যাংকিং, ওয়ালেট)। আপনার কার্ড বা UPI তথ্য আমরা কখনো দেখি না।',
    en: 'Payment happens on Razorpay (UPI, card, netbanking, wallet). We never see your card or UPI details.',
  },
  'bk.secure.dodo': {
    bn: 'পেমেন্ট হয় Dodo Payments-এর নিরাপদ পাতায়, তারপর আপনাকে এখানে ফিরিয়ে আনা হবে। আপনার কার্ডের তথ্য আমরা কখনো দেখি না।',
    en: 'You’ll pay on Dodo Payments’ secure page, then come straight back here. We never see your card details.',
  },
  'bk.step2.dodo': { bn: 'Dodo Payments-এ পেমেন্ট', en: 'Pay on Dodo Payments' },
  'bk.provider': { bn: 'কীভাবে পেমেন্ট করবেন', en: 'How would you like to pay?' },
  'bk.provider.razorpay': { bn: 'Razorpay — UPI, কার্ড, নেটব্যাংকিং, ওয়ালেট', en: 'Razorpay — UPI, card, netbanking, wallet' },
  'bk.provider.dodo': { bn: 'Dodo Payments — দেশি ও বিদেশি কার্ড', en: 'Dodo Payments — Indian & international cards' },
  'bk.confirming': { bn: 'পেমেন্ট নিশ্চিত করা হচ্ছে… এই পাতা বন্ধ করবেন না।', en: 'Confirming your payment… please keep this page open.' },
  'bk.dodoFailed': {
    bn: 'পেমেন্ট সম্পূর্ণ হয়নি, টাকা কাটেনি। আবার চেষ্টা করতে স্লটটি নতুন করে বুক করুন।',
    en: 'The payment didn’t go through and nothing was charged. Book the slot again to retry.',
  },
  'bk.mockText': { bn: 'Razorpay কী এখনো যোগ করা হয়নি — এটা পরীক্ষার পেমেন্ট, আসল টাকা কাটবে না।', en: 'Razorpay keys aren’t added yet — this is a test payment; no real money moves.' },
  'bk.mockPay': { bn: 'পরীক্ষামূলক পেমেন্ট {price}', en: 'Test payment {price}' },
  'bk.cancel': { bn: 'বাতিল', en: 'Cancel' },
  'bk.dismissed': {
    bn: 'পেমেন্ট সম্পূর্ণ হয়নি। স্লটটি ১৫ মিনিট আপনার জন্য রাখা আছে — আবার চেষ্টা করুন।',
    en: 'Payment wasn’t completed. The slot is held for you for 15 minutes — try again.',
  },
  'bk.doneTitle': { bn: 'পেমেন্ট সফল — ধন্যবাদ!', en: 'Payment received — thank you!' },
  'bk.doneText': {
    bn: 'আপনার বিজ্ঞাপন এখন যাচাইয়ের অপেক্ষায়। ২৪ ঘণ্টার মধ্যে চালু হলে হোয়াটসঅ্যাপে জানাব। কোনো কারণে চালাতে না পারলে পুরো টাকা ফেরত।',
    en: 'Your ad is now waiting for review. We’ll WhatsApp you when it’s live, within 24 hours. If we can’t run it, you’ll get a full refund.',
  },
  'bk.ref': { bn: 'বুকিং নম্বর', en: 'Booking reference' },
  'bk.doneWa': { bn: 'হোয়াটসঅ্যাপে জানান', en: 'Tell us on WhatsApp' },
  'bk.doneWaText': { bn: 'নমস্কার, আমি {site}-এ বিজ্ঞাপনের পেমেন্ট করেছি। বুকিং নম্বর: {ref} ({business})', en: 'Hello, I have paid for an ad on {site}. Booking reference: {ref} ({business})' },
  'bk.err.required': { bn: 'এটা দিতে হবে', en: 'Required' },
  'bk.err.length': { bn: 'দৈর্ঘ্য ঠিক নেই', en: 'Too short or too long' },
  'bk.err.invalid': { bn: 'ঠিক নেই — একবার দেখে নিন', en: 'Doesn’t look right — please check' },
  'bk.err.too_large': { bn: 'ফাইল ৩০০ KB-এর বেশি', en: 'File is larger than 300 KB' },
  'bk.err.bad_type': { bn: 'শুধু PNG, JPG বা WebP ছবি', en: 'Only PNG, JPG or WebP images' },
  'bk.err.form': { bn: 'কয়েকটি ঘর ঠিক করে আবার চেষ্টা করুন।', en: 'Please fix the highlighted fields and try again.' },
  'bk.err.slot_taken': { bn: 'দুঃখিত, এই স্লট এইমাত্র বুক হয়ে গেছে।', en: 'Sorry, this slot was just booked.' },
  'bk.err.pandal_taken': { bn: 'বাছাই করা কোনো প্যান্ডেলে ইতিমধ্যে বিজ্ঞাপন আছে — অন্য প্যান্ডেল বাছুন।', en: 'One of the chosen pandals already has an ad — pick another.' },
  'bk.err.rate_limited': { bn: 'অনেকবার চেষ্টা হয়েছে — একটু পরে আবার চেষ্টা করুন।', en: 'Too many attempts — please try again a little later.' },
  'bk.err.payments_not_configured': { bn: 'অনলাইন পেমেন্ট এখনো চালু হয়নি — হোয়াটসঅ্যাপে বুক করুন।', en: 'Online payment isn’t switched on yet — please book on WhatsApp.' },
  'bk.err.generic': { bn: 'কিছু একটা গোলমাল হয়েছে। আবার চেষ্টা করুন বা হোয়াটসঅ্যাপে জানান।', en: 'Something went wrong. Please try again or message us on WhatsApp.' },
  'bk.err.verify': {
    bn: 'পেমেন্ট হয়েছে কিনা নিশ্চিত হতে পারিনি। টাকা কেটে থাকলে চিন্তা করবেন না — আমরা মিলিয়ে দেখব। বুকিং নম্বরসহ হোয়াটসঅ্যাপে জানান।',
    en: 'We couldn’t confirm the payment. If money was debited, don’t worry — we’ll reconcile it. Message us on WhatsApp with your booking reference.',
  },
  'slot.dhak': { bn: '"ঢাক সৌজন্যে …"', en: '“Dhak presented by …”' },
  'slot.dhak.where': { bn: 'হোম পেজে ঢাক বাজানোর অংশে', en: 'Under the dhak on the home page' },
  'slot.countdown': { bn: '"মতামত সৌজন্যে …"', en: '“Poll by …”' },
  'slot.countdown.where': { bn: 'হোম পেজের মতামত কার্ডের নিচে', en: 'Below the home-page poll' },
  'slot.map-partner': { bn: 'প্যান্ডেল ম্যাপ পার্টনার', en: 'Pandal map partner' },
  'slot.map-partner.where': { bn: 'প্যান্ডেল ম্যাপের মাথায়', en: 'Top of the pandal map page' },
  'slot.pandal-nearby': { bn: '"কাছেই খাবার" — প্যান্ডেল কার্ডে', en: '“Eat nearby” on pandal cards' },
  'slot.pandal-nearby.where': {
    bn: 'আপনার দোকানের কাছের প্যান্ডেলগুলোর কার্ডে (প্রতি এলাকা)',
    en: 'On the cards of pandals near your shop (per area)',
  },
};
